webpro/reveal-md

bin/server-cli.js
bin/server.js
template/reveal.html

Manifest JSON file to configure more reveal.js options

---

bin/server-cli.js
bin/server.js
package.json

1. fixed 'default' theme, now it is 'black' according to reveal.js 3.0
2. express fixes

updated npm dependencies

---

template/reveal.html

One line change to add the ability to include LaTeX in your markdown.

Adding MathJax support

---

bin/server.js

Fix printFile to be consistent between console.log and reveal.js print-pdf

---

README.md

as suggested in issue https://github.com/webpro/reveal-md/issues/49

Added section explaining custom slide attributes and background images

---

bin/cli.js
bin/server.js
template/reveal.html

(partly) closes #47 .
Unfortunately printing does not work well with the static exported presentation.

static html export to stdout

---

bin/cli.js
bin/server.js
template/reveal.html

feat(title): add option to pass title via cli

---

README.md
bin/cli.js
bin/server.js
template/reveal.html

PR for adding support for injecting custom scripts into the presentation. I think this is useful when you want to write some hacks for Reveal or force fragmentize all `ul>li` elements.

Support for custom script injection

---

package.json

add license field to package.json as defined within README.md

docs: add MIT license to package.json

---

README.md

just putting the theme name is enough

css extension and path are messing stuff up

---

lib/template/reveal.html

This way one can alter 'options'

Move Reveal.initialize after injected scripts

---

lib/options.js

add: export pdf with chrome by adding the print-pdf URL query.

---

README.md

I was annoyed with scrolling so decided to open a PR to link up the feature list. 😄  Thanks for creating such a great tool!

Hyperlinked each feature to its heading in the readme

---

.gitignore
lib/options.js
lib/render.js
lib/static.js
lib/template/listing.html
lib/template/reveal.html
test/render.spec.js

Has requested in #164 and need by me
Just use 
reveal-md --static for render static from the root
reveal-md dir/ --static for render from a dir

Feature : Render static dir

---

lib/config.js
lib/static.js

This PR fixes two bugs related to embedding several scripts, please see the commit messages. I not so sure about the second commit, and can remove it if you want me to.

Fix multiscripts

---

CONTRIBUTING.md
bin/reveal-md.js
lib/config.js
lib/render.js

Pass watch option along to website template.

---

README.md
lib/config.js
lib/server.js
lib/util.js

Hi, 
I'd like to resolve #261 here, the feature would be useful to me too. I've ran test and lint on windows, have nothing else handy right now.

feat(favicon): add a check for custom favicon

---

.dockerignore
Dockerfile
README.md

Hello all,
I wanted to use your awesome module, but don't want to need node & npm dependencies locally... So I packaged it into docker.
Would you be interested in integrating it?
Thanks for this very easy setup tool :)

Add docker packaging

---

lib/server.js

Using things like iTerm2 I can hit cmd and click a link to open it.

Make server URL "cmd + click"able

---

bin/reveal-md.js
test/program.spec.js

need this in order to cause CI to report static site generation failure

exit on error

---

Dockerfile

set /slides as workdir instead of /app

---

README.md

Fixed docker live reload command for issue https://github.com/webpro/reveal-md/issues/366

Fixes isue #366

---

lib/static.js

RE for HTML img sources

---

package-lock.json
package.json

Fixes: #372 
Since technically the new version is recent enough.

deps: update to reveal.js 4.1.1

---

lib/template/reveal.html

add defaults for `slideNumber` and `controls` to template

---

README.md

Hi, I've add some documentation about the *Code sections*!
Tell me if you want some changes.
I haven't shift all the link references but tell me if I need to do it!

Code section part added in the README.md

---

lib/static.js

Signed-off-by: Mark Sagi-Kazar <mark.sagikazar@gmail.com>

fix: copy the correct favicon when building static site

---

lib/template/reveal.html

Initialize Mermaid for each single slide with in a stack which has the class present.

lazzy load per single slide in each stack

---

lib/config.js

fix: preprocessor argument doesn't work with Windows paths
