webpro/reveal-md

- bin/server-cli.js
- template/listing.html
- template/reveal.html
I often use a custom (branded) theme.
This PR allows for custom themes.
It will first look at the reveal.js theme directory and then merges the custom themes in the list.
When no team matches the given name, if will fall back to black.css (as it used to do)
> Allow to define custom theme

- README.md
- bin/server-cli.js
- bin/server.js
- package.json
- template/reveal.html
I like reveal-md. But what I was missing was an option to change the highlight theme for code highlighting. This PR contains this feature.
Changes:
* README.MD: Added example how to use `--highlightTheme`.
* server-cli.js: Added option for `--highlightTheme`.
* server.js: Added highlightTheme option to rendering AND static references to highlightTheme CSS file.
* package.json: Added highlight.js dependency for all highlight theme CSS files (default distribution of reveal.js only contains `zenburn` theme). 
* reveal.html: added mustache for highlightTheme parameter
> Added --highlightTheme option

- .eslintrc
- README.md
- bin/cli.js
- bin/server.js
- Prevents node_modules markdown files to be listed.
- Adds `--disableAutoOpen` option that prevents the web browser from being opened, truly useful those that runs this module inside a docker container :cof: like me :cof: 
- Updates README.md file with these new options and the custom reveal theme option which already exists.
> Some minor enhancements

- README.md
- bin/cli.js
This enables the use of a simple url for the --theme option. See #65
> Allow a url as theme parameter

- bin/cli.js
- bin/server.js
This PR causes the `--scripts` option to basically behave the same way as usual when generating static output. 
When no scripts are defined, this is just a quick fix for #69 , meaning that `--static` no longer throws an error. 
When scripts are specified, the static HTML will declare tags for them, assuming them to live in `/scripts/`. The user will need to manually copy the files to such a folder (same as they need to copy all the other reveal-related files).
> Make `--scripts` option work (minimally) when generating static output

- README.md
- bin/cli.js
- bin/server.js
allows for a script to groom the markdown before being fed to marked and revealjs. I find it useful to quickly (and dirtily) implement custom shorthands.
> add a markdown preprocessor

- lib/options.js
- lib/static.js
- package.json
This change will make static html export files contain the injected scripts, and copy these script files  into `${targetDir}/scripts/${injectedScript}`
Such as:
```
reveal-md demo/a.md --static ./build -i ./test.js
```
will get like
```
build/
...
- index.html
- scripts/
- test.js
```
> copy scripts file to static html export target scripts directory

- README.md
- bin/cli.js
- lib/defaults.json
- lib/options.js
- lib/serve.js
- lib/static.js
- lib/template/reveal.html
- test/render.spec.js
This will add:
* Custom styles as requested in Issue #94 (option selected to be -c, --css to not conflict with --separator or --static)
* Support for a reveal-md.json which stores reveal-md options with markdown files similar to reveal.json
> Add Support for custom style and a reveal-md.json

- lib/options.js
Remove configuration provided hostname and port from rendered resource paths as they will prevent reverse proxy usage and are superfluous.
It is not needed for the resource rendering to include the hostname and port, it actually prevents meaningful usage of reverse proxies (like for SSL offloading) and it increases configuration workarounds.
> Remove hostname and port from rendered resource

- README.md
- bin/cli.js
- lib/defaults.json
- lib/options.js
Hi !
These changes allow the use of custom HTML templates. These can replace the templates found in the `lib/template` directory.
The `-r` `--reveal-template` option will override the `lib/template/reveal.html` file.
The `-l` `--listing-template` option will override the `lib/template/listing.html` file.
---
Modified files include :
* `README.md` : Add a `Custom Template` section
* `bin/cli.js` : Add CLI options
* `lib/defaults.json` : Add (empty) defaults for template file paths
* `lib/options.js` : Use templates from options if provided
> Add custom template options

- README.md
README is pointing to the wrong link to default listing template. This is a fix for that for better clarity.
> Fix listing template URL

- lib/options.js
- lib/render.js
Current code in options.js doesn't work because the `query.print-pdf` property
will have an empty string as its value when the URL is like `?print-pdf`,
evaluating to false.
Even when it evaluates to true, it'll be a problem because then reveal-md
handles it like the `--print` command-line flag has been passed and tries to
invoke phantomjs.
Instead, sets `view.print` right before passing it to mustache.
> Make ?print-pdf actually work.

- lib/options.js
> Permit notesSeparator in YAML header to be passed to markdown processor

- lib/options.js
Hi there, I love this tool and have used it for years.
Today, I tried using the latest version and found it is not working when no `preprocessor` option is specified. It assumes a string value for `preprocessor`, but its default value is `false`. The tests are failing because of this as well.
This PR simply re-adds the check for `preprocessor` that was removed in https://github.com/webpro/reveal-md/commit/cfe3a7ac76ca4fac150356be64507bf839f8d57e.
Thank you!
> Make preprocessor optional again

- README.md
- lib/options.js
- lib/render.js
- lib/static.js
- test/preproc.js
- test/render.spec.js
This is a little hacky, but illustrates the idea.
render() already returns a promise, but doesn't call the preprocessor asynchronously.
This alters that behaviour so that projects such as https://github.com/commenthol/markedpp can be used as a preprocessor directly.
Without this it is very difficult to write a preprocessor function that will allow the use of asynchronous preprocessors.
> Make preprocessor function asynchronous

- package.json
Upgrade includes valid mime type lookup which fixes SVG rendering of static builds in Firefox and would resolve #181
> Upgrade image-data-uri dependency to 1.1.0

- lib/serve.js
- package.json
Replaces [open](https://github.com/pwnall/node-open) with [opn](https://github.com/sindresorhus/opn) to address this the following scary-sounding warning from `npm audit`:
```
=== npm audit security report ===
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Critical      │ …
```
> Replaces open with opn to address https://nodesecurity.io/advisories/663

- README.md
- bin/cli.js
- lib/featured-slide.js
- lib/options.js
- lib/static.js
- lib/template/reveal.html
- test/render.spec.js
[OpenGraph](http://ogp.me) metadata allows more attractive rendering output of links to static slide decks when they are shared in social media sites.
Metada is generated only when ``--absolute-url`` command line option is used to define eventual hosted url of the slide deck. This is used to create canonical url and ``og:image`` url.
Featured slide snapshot is captured during builds to be used as ``og:image``. Capturing is done using Puppeteer with similar approach than PDF generation.
Snapshot is stored in static build directory with filename `featured-slide.jpg`.
Captured slide could be selected by providing ``--featured-slide`` command line option, by default the first slide of the deck will be used.
Example slide deck with generated metadata: https://iiska.gitlab.io/elm-talk/ …
> Insert OpenGraph metadata to static builds

- lib/print.js
This allows to print slide pdfs in environments where you might have to launch chrome with '--no-sandbox'.
This is for example the case if you are running as root inside a container.
> adds usage of puppeteerLaunchArgs to print feature

- bin/cli.js
- lib/defaults.json
- lib/options.js
- lib/static.js
So I added the ability to change assets directory through `--assets-dir` option. It works only with `--static`, because there is no reason to change assets directory in "live view" mode. The default option is still `_assets`.
This resolves issue #207
> Add the ability to change assets directory

- bin/cli.js
- lib/featured-slide.js
- lib/options.js
- lib/print.js
Hi,
this adds an cli option to use a different chromium executable than the bundled one installed by puppeteer. It allows to use base images that already come with chrome preinstalled, as it is not easy to get the bundled chromium to run on alpine based images ([Run puppeteer in Docker](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker)).
The pull request also improves the puppeteer launch args handling as it is now done in one place instead of seperate handling for featured slides and printing.
It also improves the cli help texts for these options.
> Adds option for customizing the chromium executable used by puppeteer

- lib/listing.js
I'm using `reveal-md` to show [the lectures of my web programming course](https://github.com/vefforritun/vef2-2019), it replaced a lot of fragile homemade scripts and works beautifully. Excellent work!
Most of the time I'm presenting and showing examples, where the examples live in sub directories. This causes the listing overview to read _all_ `.md` files in `node_modules` sub directories. This PR fixes that.
> Ignore all node_modules folders when listing directories

- README.md
- bin/help.txt
- bin/reveal-md.js
- lib/config.js
- lib/print.js
- test/getPageOptions.spec.js
This PR changes default page size in exported PDFs to the same as configured slide size.
It also allows to set custom page format using `--print-size` CLI option.
Resolves #263.
> Remove white margins in exported PDFs

- demo/e.md
- lib/render.js
- lib/static.js
- lib/util.js
This is a follow-up to #265 which got recently closed.
I was unable to reproduce the issue with linking. I am on macOS 10.15 with Node v10.17.0 (I have also tried v12.12.0 with the same result).
My suspicion is that maybe we are not awaiting for the whole array of promises from `copyAssetsAndWriteFile` to resolve, so I have added `Promise.all` around the return value. Other than that I have rebased the PR, removed unnecessary `async`, and added an example to `demo` folder. Most of the hard work has been already done by @lukaszkostrzewa, I would just like to help to get this fix through.
> Copy assets specified in YAML Front matter for a static build

- lib/config.js
- lib/render.js
- lib/template/listing.html
- lib/template/reveal.html
- test/render.spec.js
The [documentation](https://github.com/webpro/reveal-md#theme) states themes can be referenced by URL, which seems to have been broken since the feature was implemented in #66. This PR fixes this for the option `theme`, but not `highlightTheme`.
Currently the template renders the theme with an URL incorrectly as `href="/https://example.org/style.css"`.
> Fix usage of theme URL

- .github/workflows/dockerimage.yml
This PR brings automatic image publication to docker.
This is implemented with https://github.com/jerray/publish-docker-action, which provides a simple way to publish tagged images on dockerhub.
I ran this automation in my fork and by default it produced this image (tagged by the branch name which is default):
https://hub.docker.com/repository/docker/davidovich/reveal-md
@webpro when merged, you should add your dockerhub username and password (in your github repository settings->secrets), and I believe that your account on dockerhub differs, so add also a 
```yaml
repository: webpronl/reveal-md
```
like so: 
```
- name: Publish
uses: jerray/publish-docker-action@v1.0.3
with:
username: ${{ secrets.DOCKER_USERNAME }}
password: ${{ secrets.DOCKER_PASSWORD }}
repository: webpronl/reveal-md …
```
> Add docker automation

- package-lock.json
- package.json
0.9.0 broke livereload when it implented public npm consumption instead
of vendoring.
See https://github.com/napcs/node-livereload/pull/140 which made the
change and
https://github.com/napcs/node-livereload/pull/142 (not merged) which tries to fix it.
fixes #305
> revert livereload to 0.8.2

- bin/reveal-md.js
This also allows correctly exiting the docker container when
using docker run.
fixes #307
> add SIGINT handler for properly closing reveal-md

- Dockerfile
this is based on revert live-reload fix (because it depends on having a package-lock.json file)
see https://github.com/webpro/reveal-md/commit/75704e72148d4efdc877a6e0a546cbc25dc405c4
> Optimize dockerfile for development

- README.md
- bin/help.txt
- lib/config.js
- lib/defaults.json
- lib/listing.js
- lib/static.js
- lib/util.js
- test/fixtures/a.md
- test/fixtures/slides.md
- test/fixtures/sub/c.md
- test/fixtures/sub/slides.md
- test/util.spec.js
Hello, this is primarily a proposal based on my personal proof of concept. If you agree to include this feature, I will polish the PR to include tests and documentation.
My motivation: I have multiple MD files in subdirectories and I would like to convert all slides at once for shared assets and listing.  However, there are also some "meta" files like `README.md` which should not be processed by reveal-md. Currently all MD files are converted to HTML. Also if some subfolder contains e.g. `node_modules/` directory, reveal-md also processes MD files recursively in there, making the final listing pretty unusable.
Looking at the code, I noticed there's a hardcoded glob pattern for listing MD files for conversion as `**/*.md`, so I just exposed it for configuration as `slidesGlob` option. Now …
> Add option to whitelist MD files for conversion

- lib/static.js
- lib/template/reveal.html
- test/render.spec.js
Hello,
The [custom favicon](https://github.com/webpro/reveal-md#custom-favicon) work great in server mode however the favicon doesn't work in static build.
I use the same logic, take the favicon.ico at the root if it exists, otherwise use the default favicon.ico.
> Manage favicon and custom favicon in static build

- lib/static.js
I use `index.md` for my top level markdown and I started getting the error
```
❏ .site/index.html → .site/index.html
Error: Source and destination must not be the same.
```
after https://github.com/webpro/reveal-md/blob/841df3bfc9b20a6239db78cd3c011a564c427f32/lib/static.js#L86 was changed from link to cp.
This avoids the cp in this case.
> don't copy if md is named index

- README.md
Feel free to make changes if you'd like, I think the instructions are reasonably clear though.
> Added DeckTape Docker printing instructions to README

- lib/static.js
According to the [README](https://github.com/webpro/reveal-md/blob/master/README.md#custom-favicon), the custom favicon should be placed in 
> the directory with the markdown files.
If I understand the code from `static.js` correctly, this path is the one from `getPath()` (which is also used as 1st argument when calling `writeMarkupFiles` in line 112). 
However, in the current code, the resulting path for `faviconPath` will always be the folder where the command is executed (`process.cwd()`).
With this Pull request, I propose to add `getPath()` to the list of paths to join in order to be able to copy the custom favicon.
> Fix faviconPath

- lib/listing.js
- lib/template/listing.html
Allows to use data from file meta (front matter) in listing template
https://github.com/webpro/reveal-md/issues/346
> Allow usage front-matter data in listing template

- Dockerfile
Node's LTS slim container is based on Debian, which replaces vanilla
`/bin/sh` with `/bin/dash`.  This causes problems for things which are
expecting vanilla `/bin/sh`, like GitLab runner's docker executor.  An
easy solution is to simply replace Debian with something equally as
slim -- Alpine Linux.
> Switch to Alpine based container

- README.md
Based on information from https://github.com/gitpitch/gitpitch
> March 1, 2021: Service on gitpitch.com has been shutdown permanently.
This PR change the URL for gitpitch to the gitpitch project instead of gitpitch.com
> Fix gitpitch URL since gitpitch.com is shutting down

- lib/static.js
This is needed since markdown files could be modified by preprocessor
> bugfix: search for images on rendered html files

- lib/config.js
this fix was need to load custom css when exporting to static html
> bugfix: relative asset paths have to start with .

- lib/static.js
This fix deals issues in #408.
Matching regex patterns that look like markdown or html image tags may fail when such patterns exist inside strings or code, such as:
```markdown
* Images below should not be included.
```html
<p>
This image doesn't exist, but it's okay because it's just source code.
</p>
```
````
Moreover, currently any un-existing images during static run exits the program, which is not what a user may want.
This does the following:
* Instead of using regex match, transform into html and apply only to HTML image tags.
* catch any image copies, and ignore the error (prints out warning)
> Fix incorrect image copies [#408]

- lib/render.js
This pull request adds a check to the rendering function to ensure that the provided path is within the initial directory. If it isn't, it responds with 401: Forbidden and a relevant message. The `filePath.startsWith` check should be sufficient because `path.join` (used to create `filePath`) and `path.resolve` (used to create `dir`) both normalize the resulting paths, so all `..` sections will be removed.
Closes #409.
> Ensure rendered files are inside the initial directory

- lib/render.js
This patch will do two things : 
- Add a try{}catch{} block to avoid the webserver to crash if someone try to reach a non-existent file (sort of DoS)
- Add a sanitize function to replace, after the urldecode function, all the ".." by nothing, and called himself if someone try to bypass the restriction
> Add patch for arbitrary file read

- bin/reveal-md.js
This message is helpful in cases where the URL is not automatically
opened. E.g. when running the application via Docker.
> Print the initial Slide's URL on statup

- .github/workflows/publish-container.yaml
- LICENSE
I'm working with the Docker metadata action on an another project, and came back to this for reference.  Then however, I noticed that it was missing something.  This pull request tries to rectify that.  As it now only pushes full SemVer tags.
1. This change will now push the tags `6` and `6.0` too.
2. I added a license file so that GitHub were able to detect a repository license and it would autofill the metadata without some custom label.
For number 2, I'm looking into [license-year-updater](https://github.com/p3lim/license-year-updater) for updating it annually, but it's lacking the option to just bump the year in place instead of bumping the range.
---
Ed1t: I guess you need to trigger it for the login action to be able to use the login details?
> Fix Docker metadata to push more tags

- lib/listing.js
- lib/template/listing.html
This adds a date field to the listings page, which provides useful for automatic deployment (e.g. GitHub actions).
> Added the date field to Mustache

- README.md
- lib/config.js
- lib/listing.js
- lib/render.js
This fixes https://github.com/webpro/reveal-md/issues/439 for me.
> Fix the inclusion of a custom theme when using `--static`

- lib/static.js
This should fix comment https://github.com/webpro/reveal-md/issues/389#issuecomment-1105290037 .
> --static now also copies background images

- .editorconfig
- bin/reveal-md.js
- lib/config.js
- lib/constants.js
- lib/featured-slide.js
- lib/listing.js
- lib/print.js
- lib/render.js
- lib/server.js
- lib/static.js
- lib/util.js
- package-lock.json
- package.json
- test/getPageOptions.spec.js
- test/preproc.js
- test/program.spec.js
- test/render.spec.js
- test/slidify.spec.js
- test/util.spec.js
This is a PR to facilitate the upgrade to Reveal.js 5.0.0 as mentioned in https://github.com/webpro/reveal-md/issues/462 and https://github.com/hakimel/reveal.js/issues/3517 . Although Reveal.js hasn't been updated in this PR, all the rest has.
Normally, there should be no or very small breaking changes. All the unit tests and my personal use case work as expected, but I can't test everything and everyway reveal-md has been used, and many files have been edited in some way in the code base.
> Update reveal-md to ES modules and updated all dependencies

- bin/reveal-md.js
- lib/config.js
- lib/util.js
- test/program.spec.js
- test/util.spec.js
I did all my development on Linux. Now I was experimenting on a Windows system and `reveal-md` failed on me. Apparently I introduced 2 bugs for Windows:
- The new `globSync` functions have gotten built in support for Windows paths, so I had to explicitly configure these to use POSIX paths.
- The code I used to simulate `__dirname` was not crossplatform, so I looked up a crossplatform solution and found https://nodejs.org/api/url.html#url_url_fileurltopath_url (inspired by https://stackoverflow.com/questions/46745014/alternative-for-dirname-in-node-js-when-using-es6-modules )
Sorry for the bug, I only realized it now ...
> Fixed regression on Windows systems

- lib/print.js
I encountered an issue with the loading of js assets and custom fonts when attempting to generate a PDF. This resulted in either empty or poorly formatted pdf. Upon investigation, I determined that the problem was related to the `waitUntil` option of Puppeteer's `goto()` method.
There are several options available for the `waitUntil` parameter, including `load`, `domcontentloaded`, `networkidle0`, and `networkidle2`. You can find detailed descriptions of these options [here](https://cloudlayer.io/blog/puppeteer-waituntil-options/) and a discussion in  [this GitHub issue](https://github.com/peterbe/minimalcss/issues/205#issuecomment-391389969).
I changed the `waitUntil` value to `networkidle0`, and this adjustment successfully resolved the problem, allowing the assets and fonts to load …
> fix(print-pdf): wait untill all resources are loaded

- package-lock.json
- package.json
Thanks to https://github.com/hakimel/reveal.js/issues/3517 we can call the markdown plugin again, thus we are able to update to Reveal.js 5.0.2.
> Reveal.js can now be updated to 5.0.2

- package-lock.json
- package.json
I had to remove `"eslint-plugin-import": "2.29.1",` as it has no support for eslint v9. I don't know if it was important as it is only a dev dependancy?
> Updated dependancies
